services:
  minio:
    image: minio/minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes: ["minio_data:/data"]

  createbuckets:
    image: minio/mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "sleep 5; /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; /usr/bin/mc mb myminio/mlflow --ignore-existing; exit 0;"

  mlflow:
    image: python:3.11-slim
    ports: ["5000:5000"]
    depends_on: [minio]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
    command: >
      /bin/sh -c "pip install mlflow boto3 && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://mlflow/ --host 0.0.0.0 --allowed-hosts 'mlflow:5000,localhost:5000'"

  api:
    image: ghcr.io/gprodi/ml_zero_downtime/mlfactory-api:latest
    ports: ["8000:8000"]
    depends_on: [mlflow]
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}

  front:
    image: ghcr.io/gprodi/ml_zero_downtime/mlfactory-front:latest
    ports: ["8501:8501"]
    depends_on: [api]
    environment:
      API_URL: ${API_URL}

    # --- BASE DE DONNÉES PREFECT ---
  prefect-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prefect_pass}
      POSTGRES_DB: prefect
    volumes:
      - prefect_db_data:/var/lib/postgresql/data

  # --- SERVEUR PREFECT ---
  prefect:
    image: prefecthq/prefect:3-python3.11
    restart: always
    ports: ["4200:4200"]
    depends_on: [prefect-db]
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:${POSTGRES_PASSWORD:-prefect_pass}@prefect-db:5432/prefect
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_UI_API_URL: http://localhost:4200/api

  # --- LE WORKER DOCKER ---
  train_worker:
    # CORRECTION : Alignement avec l'API et le Front
    image: ghcr.io/gprodi/ml_zero_downtime/mlfactory-train:latest
    depends_on: [mlflow, minio, prefect]
    restart: on-failure
    # Le worker démarre et écoute le pool défini dans le yaml
    command: prefect worker start --pool 'docker-pool'
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

volumes:
  minio_data:
  prefect_db_data: # Ajout du volume pour la persistance Postgres