services:
  # --- 1. LE STOCKAGE DES ARTEFACTS (MINIO) ---
  minio:
    image: minio/minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes: 
      - minio_data:/data

  # --- 3. LE REGISTRE ET TRACKING ML (MLFLOW) ---
  mlflow:
    image: python:3.11-slim
    ports: ["5000:5000"]
    depends_on: [minio]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
    # Correction de la faille : On place la base SQLite dans un dossier monté en volume
    command: >
      /bin/sh -c "pip install mlflow boto3 && mlflow server --backend-store-uri sqlite:////mlflow_db/mlflow.db --default-artifact-root s3://mlflow/ --host 0.0.0.0 --allowed-hosts 'mlflow:5000,localhost:5000'"
    volumes:
      - mlflow_data:/mlflow_db

  # --- 4. LA BASE DE DONNÉES DE L'ORCHESTRATEUR (POSTGRESQL) ---
  prefect-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prefect_pass}
      POSTGRES_DB: prefect
    volumes:
      - prefect_db_data:/var/lib/postgresql/data

  # --- 5. LE SERVEUR D'ORCHESTRATION (PREFECT) ---
  prefect:
    image: prefecthq/prefect:3-python3.11
    restart: always
    ports: ["4200:4200"]
    depends_on: [prefect-db]
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:${POSTGRES_PASSWORD:-prefect_pass}@prefect-db:5432/prefect
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_UI_API_URL: http://localhost:4200/api

  # --- 6. LE WORKER D'ENTRAÎNEMENT DISTRIBUÉ ---
  train_worker:
    image: ghcr.io/gprodi/ml_zero_downtime/mlfactory-train:latest
    depends_on: [mlflow, minio, prefect]
    restart: on-failure
    command: prefect worker start --pool 'docker-pool'
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

  # --- 7. L'API D'INFÉRENCE ---
  api:
    image: ghcr.io/gprodi/ml_zero_downtime/mlfactory-api:latest
    ports: ["8000:8000"]
    depends_on: [mlflow]
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}

  # --- 8. L'INTERFACE UTILISATEUR (STREAMLIT) ---
  front:
    image: ghcr.io/gprodi/ml_zero_downtime/mlfactory-front:latest
    ports: ["8501:8501"]
    depends_on: [api]
    environment:
      API_URL: ${API_URL}

# --- DÉCLARATION DES VOLUMES PERSISTANTS ---
volumes:
  minio_data:
  mlflow_data:
  prefect_db_data: